"""Added note field to TaskLog

Revision ID: 7918e630adb0
Revises: c9969da7f008
Create Date: 2020-08-14 02:55:36.644103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7918e630adb0'
down_revision = 'c9969da7f008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TaskLog', sa.Column('note', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TaskLog', 'note')
    # ### end Alembic commands ###
